# Generated by Django 5.1.2 on 2024-11-12 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_genero_alter_uf_options_alter_uf_sigla_cidade_autor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='editora',
            options={'verbose_name': 'Editora', 'verbose_name_plural': 'Editoras'},
        ),
        migrations.RemoveField(
            model_name='editora',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='editora',
            name='nome',
        ),
        migrations.AddField(
            model_name='autor',
            name='cpf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autor',
            name='data_nasc',
            field=models.DateField(default='2000-01-01', verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='autor',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='autor',
            name='telefone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='editora',
            name='cnpj',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='editora',
            name='data_fundacao',
            field=models.DateField(default='2000-01-01', verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='editora',
            name='razao_social',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='autor',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='editora',
            name='site',
            field=models.CharField(),
        ),
    ]
